[package]
name = "rust_fundamentals1"
version = "0.1.0"
edition = "2021"
authors = ["Jeni Rainer <jenirainer@icloud.com>"]
description = "A Rust project"
license = "MIT"

[dependencies]
tempfile = "3.21.0"
flexi_logger = "0.31.1"
log = "0.4.27"